// Regenerates lib/assets.generated.js — the base64 payloads the cards inline.
//
// GitHub serves README images through camo, and an SVG loaded as an <img> runs
// in "secure static mode": every external reference (webfont, screenshot, CSS)
// is blocked. Anything the card needs therefore has to travel inside the file
// as a data: URI, so this script bakes two things into one module:
//
//   FONTS  — latin subsets of Geist / Geist Mono, the portfolio's typefaces,
//            pulled from Google Fonts. Geist is variable, so one file covers
//            every weight the cards use.
//   THUMBS — 640x360 WebP screenshots of the featured projects, resized from
//            the portfolio's public/images with sips + cwebp.
//
// Run it whenever a screenshot changes:
//   node scripts/build-assets.mjs
//
// Requires macOS `sips` + `cwebp` (brew install webp) and network access. The
// output is committed, so deploys never depend on either.
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const PORTFOLIO_IMAGES =
    process.env.PORTFOLIO_IMAGES ||
    join(process.env.HOME, "Documents/Projects/portfolio/public/images");

// Matches lib/featured.js — keyed by project id.
const SHOTS = [
    ["interviewpilot", "InterviewPilot.png"],
    ["pneumoai", "project1.png"],
    ["coinpush", "project3.png"],
    ["algoplus", "algoplus.png"],
];

const UA =
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

// Google returns one @font-face per unicode subset; the latin block is the one
// whose range starts at U+0000 and it is all the cards ever render.
async function latinWoff2(familyQuery) {
    const cssUrl = `https://fonts.googleapis.com/css2?family=${familyQuery}&display=swap`;
    const css = await (await fetch(cssUrl, { headers: { "User-Agent": UA } })).text();
    const blocks = css.split("@font-face").slice(1);
    const latin = blocks.find((b) => /unicode-range:\s*U\+0000-00FF/.test(b));
    if (!latin) throw new Error(`No latin subset for ${familyQuery}`);
    const url = latin.match(/url\((https[^)]+)\)/)[1];
    const buf = await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer();
    return Buffer.from(buf).toString("base64");
}

function thumbBase64(file, tmp) {
    const src = join(PORTFOLIO_IMAGES, file);
    if (!existsSync(src)) throw new Error(`Missing screenshot: ${src}`);
    const png = join(tmp, "resized.png");
    // Width-fit to 640, then centre-crop to a clean 16:9 so every card slot
    // holds the same shape regardless of how the screenshot was captured.
    execFileSync("sips", ["-Z", "640", src, "--out", png], { stdio: "ignore" });
    execFileSync("sips", ["-c", "360", "640", png], { stdio: "ignore" });
    const webp = join(tmp, "out.webp");
    execFileSync("cwebp", ["-q", "72", "-quiet", png, "-o", webp]);
    return readFileSync(webp).toString("base64");
}

const kb = (b64) => `${(b64.length / 1024).toFixed(1)} KB`;

async function main() {
    const tmp = mkdtempSync(join(tmpdir(), "profile-assets-"));
    try {
        const [geist, geistMono] = await Promise.all([
            // Geist is variable, so one file serves every display weight.
            // The mono is only ever used at one weight, so take the static
            // instance — a third of the size of the variable file.
            latinWoff2("Geist:wght@400..800"),
            latinWoff2("Geist+Mono:wght@500"),
        ]);
        console.log(`Geist       ${kb(geist)}`);
        console.log(`Geist Mono  ${kb(geistMono)}`);

        const thumbs = SHOTS.map(([id, file]) => {
            const b64 = thumbBase64(file, tmp);
            console.log(`${id.padEnd(11)} ${kb(b64)}`);
            return [id, b64];
        });

        const out = `// GENERATED by scripts/build-assets.mjs — do not edit by hand.
// Base64 payloads inlined into every card: an SVG rendered as a GitHub README
// image cannot fetch webfonts or screenshots, so they ship inside the file.

export const FONT_GEIST_WOFF2 =
    "${geist}";

export const FONT_GEIST_MONO_WOFF2 =
    "${geistMono}";

// 640x360 WebP screenshots, keyed by the project ids in lib/featured.js.
export const THUMBS = {
${thumbs.map(([id, b64]) => `    ${id}:\n        "${b64}",`).join("\n")}
};
`;
        writeFileSync(new URL("../lib/assets.generated.js", import.meta.url), out);
        console.log(`\nWrote lib/assets.generated.js (${(out.length / 1024).toFixed(0)} KB)`);
    } finally {
        rmSync(tmp, { recursive: true, force: true });
    }
}

main().catch((e) => {
    console.error(e.message);
    process.exit(1);
});
